name: TryHackMe Update Badge
on:
  schedule:
    - cron: '0 0 * * *'     # runs daily
  workflow_dispatch:         # allows manual run

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update THM badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Cyberant"
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update TryHackMe badge" || echo "No changes to commit"
          git push
